import React, { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { FiArrowRight, FiAward, FiClock } from 'react-icons/fi';
import { HomeSectionLink, HOME_SECTIONS } from '../../utils/homeSectionNavigation.jsx';
import SectionHeading from '../common/SectionHeading';
import { SkeletonGrid, ErrorState, EmptyState } from '../common/StateViews';
import { publicService } from '../../services/publicService';

const LeadershipCard = ({ master, index }) => <motion.article initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.45, delay: index * 0.06 }} className="master-card master-card--leadership group"><div className="master-card-photo relative aspect-[1.08/1] overflow-hidden">{master.photo_url && <img src={master.photo_url} alt={master.name} className="w-full h-full object-cover object-top transition-transform duration-500 group-hover:scale-[1.05]" loading="lazy" />}<div className="master-card-photo-overlay" /><span className="master-card-role absolute top-3 left-3 rounded-full">{master.role}</span></div><div className="p-5 sm:p-6 text-left"><span className="block h-px w-9 bg-brass-500/60 mb-3" /><h3 className="font-display text-xl font-semibold sm:text-[1.35rem] text-parchment-100 leading-tight">{master.name}</h3><MasterDetails master={master} />{master.bio && <p className="mt-4 text-sm leading-relaxed text-slate-300">{master.bio}</p>}</div></motion.article>;

const ProgrammeCard = ({ master, index }) => <motion.article initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.4, delay: index * 0.05 }} className="master-card master-card--programme p-5 sm:p-6 text-left"><p className="text-[0.65rem] font-bold uppercase tracking-[0.16em] text-brass-400">{master.programme || 'Programme Coach'}</p><span className="block h-px w-9 bg-brass-500/60 my-4" /><h3 className="font-display text-xl font-semibold text-parchment-100 leading-tight">{master.name}</h3><MasterDetails master={master} /></motion.article>;

const MasterDetails = ({ master }) => (master.specialization || master.experience_years) && <div className="mt-4 grid grid-cols-2 gap-3">{master.specialization && <div className="master-card-stat"><div className="flex items-center gap-1.5 text-brass-500"><FiAward className="text-xs shrink-0" /><span className="text-[0.6rem] font-semibold uppercase tracking-[0.1em]">Specialty</span></div><p className="mt-1 text-parchment-100 text-sm leading-snug">{master.specialization}</p></div>}{master.experience_years && <div className="master-card-stat"><div className="flex items-center gap-1.5 text-brass-500"><FiClock className="text-xs shrink-0" /><span className="text-[0.6rem] font-semibold uppercase tracking-[0.1em]">Experience</span></div><p className="mt-1 text-parchment-100 text-sm leading-snug">{master.experience_years} years</p></div>}</div>;

const SpecialtyFilter = ({ specialties, active, onChange }) => <div className="-mx-4 mb-8 overflow-x-auto px-4 pb-1 sm:mx-0 sm:px-0" role="group" aria-label="Filter coaches by specialty"><div className="flex w-max min-w-full justify-start gap-2 sm:justify-center">{['All', ...specialties].map((specialty) => <button key={specialty} type="button" aria-pressed={active === specialty} onClick={() => onChange(specialty)} className={`whitespace-nowrap rounded-full border px-4 py-2 text-xs font-semibold uppercase tracking-wide transition-all duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brass-400 ${active === specialty ? 'bg-brass-500 border-brass-500 text-onaccent shadow-[0_8px_24px_-12px_rgba(224,133,50,0.8)]' : 'border-parchment-100/15 text-slate-300 hover:border-brass-400 hover:text-brass-400'}`}>{specialty}</button>)}</div></div>;

const Masters = ({ limit, showViewAll = false, pageView = false }) => {
  const [masters, setMasters] = useState(null); const [error, setError] = useState(false); const [activeSpecialty, setActiveSpecialty] = useState('All');
  useEffect(() => { publicService.getMasters().then(({ data }) => setMasters(data.data)).catch(() => setError(true)); }, []);
  const { leadership, programmeMasters, specialties } = useMemo(() => {
    const ordered = [...(masters || [])].sort((a, b) => Number(a.display_order) - Number(b.display_order));
    const programmeMasters = ordered.filter((master) => master.master_type === 'programme');
    return { leadership: ordered.filter((master) => master.master_type === 'leadership'), programmeMasters, specialties: [...new Set(programmeMasters.map((master) => master.specialization?.trim()).filter(Boolean))] };
  }, [masters]);
  const visibleProgrammeMasters = activeSpecialty === 'All' ? programmeMasters : programmeMasters.filter((master) => master.specialization?.trim() === activeSpecialty);
  const isLoading = !masters && !error;
  const previewLeadership = leadership.slice(0, limit || leadership.length);
  const previewProgramme = programmeMasters.slice(0, limit || programmeMasters.length);
  const renderGroups = (isFullPage) => <div className={isFullPage ? 'space-y-16' : 'space-y-10'}>{leadership.length > 0 && <section aria-labelledby="leadership-heading"><div className="text-center mb-8"><h2 id="leadership-heading" className={isFullPage ? 'section-heading' : 'font-display text-2xl text-parchment-100'}>Leadership</h2><p className="mt-2 text-brass-400 font-display">Founder, director and head coach</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6 lg:gap-7">{(isFullPage ? leadership : previewLeadership).map((master, index) => <LeadershipCard key={master.id} master={master} index={index} />)}</div></section>}{programmeMasters.length > 0 && <section aria-labelledby="programme-masters-heading"><div className="text-center mb-8"><h2 id="programme-masters-heading" className={isFullPage ? 'section-heading' : 'font-display text-2xl text-parchment-100'}>Programme Masters</h2><p className="mt-2 text-brass-400 font-display">Specialist coaches for every discipline</p></div>{isFullPage && <SpecialtyFilter specialties={specialties} active={activeSpecialty} onChange={setActiveSpecialty} />}<motion.div layout className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5 lg:gap-6">{(isFullPage ? visibleProgrammeMasters : previewProgramme).map((master, index) => <ProgrammeCard key={master.id} master={master} index={index} />)}</motion.div>{isFullPage && visibleProgrammeMasters.length === 0 && <EmptyState message="No coaches available" />}</section>}</div>;
  if (pageView) return <section id="masters" className="py-12 sm:py-16"><div className="container-xl"><header className="max-w-3xl mx-auto text-center mb-16"><p className="eyebrow mb-3">Our Masters</p><h1 className="section-heading">Trained under dedicated, experienced coaches</h1><p className="mt-4 text-slate-300 text-sm sm:text-base leading-relaxed">Our leadership and programme masters bring expertise, discipline and care to every session.</p></header>{isLoading && <SkeletonGrid count={6} className="sm:grid-cols-2 lg:grid-cols-3" />}{error && <ErrorState message="Couldn't load master profiles right now." />}{masters?.length === 0 && <EmptyState message="Master profiles will appear here soon." />}{masters?.length > 0 && renderGroups(true)}</div></section>;
  return <section id="masters" className="py-10"><div className="container-xl"><SectionHeading eyebrow="Our Masters" title="The people behind the discipline" subtitle="Meet the leadership and programme coaches guiding every training session." />{isLoading && <SkeletonGrid count={limit || 4} className="sm:grid-cols-2 lg:grid-cols-3" />}{error && <ErrorState message="Couldn't load master profiles right now." />}{masters?.length === 0 && <EmptyState message="Master profiles will appear here soon." />}{masters?.length > 0 && <>{renderGroups(false)}{showViewAll && <div className="mt-9 text-center"><HomeSectionLink to="/masters" section={HOME_SECTIONS.masters} className="btn-secondary">Meet Our Masters <FiArrowRight /></HomeSectionLink></div>}</>}</div></section>;
};

export default Masters;
